### ISSUE TITLE
Import entire directory as namespace

### ISSUE THREAD

**Issue by fitzage** [delucis/astro-auto-import#44] opened 2024-05-03 16:54 UTC
I’d love to be able to point this at an entire directory or subdirectory and have all the components in that directory be namespaced, so something like this:
```
imports: [
  {
    './src/components/atoms/*': ‘Atoms',
  },
];
```
and then use them like `<Atoms.MyAtom />`

Basically an expansion of the current Namespace Import to support a directory of components instead of a single file with multiple modules.

**Comment by delucis** [comment] 2024-05-03 21:29
Thanks for the feature request @fitzage! I think this is a duplicate of #20, so will close it to redirect discussion there.

**Closed as not planned by delucis** 2024-05-03 21:29 UTC
